GET http://localhost:3003/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwOGFjYzA0YjEyOGJkMjZhMGE2N2NjOSIsImlhdCI6MTYxOTc5MTgzOSwiZXhwIjoxNjE5Nzk1NDM5fQ.hsCp9VnZpfOHCFJFsEY_eW3hiXY120GaesBnFQPuZ8E

###

GET http://localhost:3003/api/blogs/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imd1aSIsImlkIjoiNjA4YWNjN2JiMTI4YmQyNmEwYTY3Y2NiIiwiaWF0IjoxNjE5NzQxNzg0LCJleHAiOjE2MTk3NDUzODR9.dWEp4Aeh8w44myB4AhwJoiQOF--iWGikMjdsv1F7oOE
###

GET http://localhost:3003/api/users

###
DELETE http://localhost:3003/api/blogs/608b4e3eb665de53b095554c HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwOGFjYzA0YjEyOGJkMjZhMGE2N2NjOSIsImlhdCI6MTYxOTc0NjE1NCwiZXhwIjoxNjE5NzQ5NzU0fQ.hoQsNBJjT7YDMO1ipi2FB8y8C9n_fPD8UNc-_OPnMXs

###
DELETE http://localhost:3003/api/blogs/609e78378773d33c504b4daf
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imd1aSIsImlkIjoiNjA4YWNjN2JiMTI4YmQyNmEwYTY3Y2NiIiwiaWF0IjoxNjIwOTk4MDE0LCJleHAiOjE2MjEwMDE2MTR9.FbMP0cgNkdIXX2fbGODZrrf0k9lXH33nD8wqEMpO7Og

###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "notes": [],
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "notes": [],
    "username": "mluukkai1",
    "name": "mluukkai1",
    "password": "mluukkai1"
}

###
PUT http://localhost:3003/api/blogs/609d5f8618187b2590e4a728 HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imd1aSIsImlkIjoiNjA4YWNjN2JiMTI4YmQyNmEwYTY3Y2NiIiwiaWF0IjoxNjIwOTI2MTM5LCJleHAiOjE2MjA5Mjk3Mzl9.NiWU5816Ae1RKTw--ZDriL-Frbxtn-ytHFCxaiTnig8

{
    "title": "new title",
    "author": "new author",
    "url": "123",
    "likes": 1,
    "id": "609d5f8618187b2590e4a728"
  }

###

POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imd1aSIsImlkIjoiNjA4YWNjN2JiMTI4YmQyNmEwYTY3Y2NiIiwiaWF0IjoxNjE5NzQ1MTYwLCJleHAiOjE2MTk3NDg3NjB9.VQpg8hdsy_rCk7Hj6LffKr33oNk9xvwV4QYcrkBYRlk

{
    "title": "blog added by gui",
    "author": "random author",
    "url": "random url",
    "likes": "500",
    "userId": "608acc7bb128bd26a0a67ccb"
}

// THIS SHOULDN'T WORK!!!!!
// TODO: THIS TOKEN WAS FOR THE GUI USER AND THE USERID INFORMED IN CONTENT
// IS FROM SUPERSUPER USER, THIS WILL BE FIXED WHEN I CREATE A FUNCTION
// TO EXTRACT THE USER FROM THE TOKEN, SO NO MORE SENDING USER WITHIN THE
// REQUEST

###

POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "gui",
    "password": "senha123"
}

###
POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "root",
    "password": "salainen"
}

###
POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json


{ "username": "mluukkai1", "password": "mluukkai1" }



###
token for gui: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imd1aSIsImlkIjoiNjA4YWNjN2JiMTI4YmQyNmEwYTY3Y2NiIiwiaWF0IjoxNjE5NzM3MzMzLCJleHAiOjE2MTk3NDA5MzN9.E411WeqxnAVvlJlX_D-oJuPXjaFyn7DHjptc7Tk_el4